tkt

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -6,29 +6,29 @@ on:
     pull_request:
         branches-ignore: [ga-ignore-*]
 jobs:
-  coding-style:
-    runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
-    steps:
+    coding-style:
+        runs-on: ubuntu-latest
+        container:
+          image: ghcr.io/epitech/coding-style-checker:latest
+        steps:
     # Fetch the repository content
-      - name: Checkout GH repository
-        uses: actions/checkout@master
+            - name: Checkout GH repository
+             uses: actions/checkout@master
 
     # Run the banana script
-      - name: Run coding-style.sh
-        run: check.sh $(pwd) $(pwd)
+              - name: Run coding-style.sh
+                run: check.sh $(pwd) $(pwd)
 
     # Return an error if the banana report file is not empty
-      - name: Report banana result
-        run: |
-          NB_ERROR=$(cat coding-style-reports.log | wc -l)
-          if [ $NB_ERROR -gt 0 ]; then
-            ERROR=$(cat coding-style-reports.log)
-            echo "::error title=$NB_ERROR errors found::$ERROR"
-            exit 1
-          fi
-          exit 0
+              - name: Report banana result
+                run: |
+                NB_ERROR=$(cat coding-style-reports.log | wc -l)
+                if [ $NB_ERROR -gt 0 ]; then
+                ERROR=$(cat coding-style-reports.log)
+                echo "::error title=$NB_ERROR errors found::$ERROR"
+                exit 1
+            fi
+            exit 0
 
     compile:
         runs-on: ubuntu-latest
