tkt bg

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -23,11 +23,11 @@ jobs:
               run: |
                 NB_ERROR=$(cat coding-style-reports.log | wc -l)
                 if [ $NB_ERROR -gt 0 ]; then
-                ERROR=$(cat coding-style-reports.log)
-                echo "::error title=$NB_ERROR errors found::$ERROR"
-                exit 1
-            fi
-            exit 0
+                  ERROR=$(cat coding-style-reports.log)
+                  echo "::error title=$NB_ERROR errors found::$ERROR"
+                  exit 1
+                fi
+                exit 0
 
     compile:
         runs-on: ubuntu-latest
